### ISSUE TITLE
[BUG] GODMode / No Death After Revival at Pillbox Hospital 

### ISSUE THREAD

**Issue by d-w00d** [qbcore-framework/qb-ambulancejob#111]
**Describe the bug**
When a player is shot and killed, then taken to PillBox hospital him or her would become glitched in God Mode. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a person mag dump you
2. Be transported to PillBox
3. Revive at the station
4. walkout 
5. get shot
6. don't die

**Expected behaviour**
This bug I am not 100% certain is 100% persistent or if it's just a random every so often issue, but we've experienced this a few times thus far and wanted to make sure it was just reported. 

**Screenshots**
https://clips.twitch.tv/OptimisticAntsyPterodactylPeanutButterJellyTime-P5Pj4tyTNHoqiURF
^ Twitch Clip - Guy with Black Cowboy Hat with Red Undershirt was just recently killed, brought to Hospital, Revived at the station, upon revival he then walked out. The rival person arrived at PIllbox then initiated gunfire, he would not die while being shot in the head. Admins arrived on the scene tried to gun him down he would not die. Unless we killed him via the Admin Menu and then Revived him he would then die. 

**Questions (please complete the following information):**
 - Updated 3 days ago
 - Nothing Custom
 - Nothing Renamed

**Additional context**
We do not have anything custom wise done to this build that would interfere with Hospital Operations, we've updated QB-AmbulanceJob to more Recent with iFaks implementation.

**Comment by d-w00d** [comment]
Furthermore to this, players hit E more than once this will do this.

**Comment by MonkeyWhisper** [comment]
I can't duplicate this by trying your steps. Seems like it's random?

**Comment by d-w00d** [comment]
What players have done is been killed, in last stance, then taken in they hit e twice while its loading and then they have it
