### ISSUE TITLE
[IDEA/HELP]

### ISSUE THREAD

**Issue by leuxum** [qbcore-framework/qb-ambulancejob#128]
hi im wondering on how i can make the death more in depth , for example when shot in the head you go straight to the dead anim , and when youre hit in the head with certain items such as a hatchet you also go straight to dead , this would just make the rp way more in depth instead of being at the last stand after being shot in the head , also a suggestion for you guys to add to future scripts

**Comment by MonkeyWhisper** [comment]
This is not a bug.
