### ISSUE TITLE
GODMODE - GLITCH | Previously Reported

### ISSUE THREAD

**Issue by d-w00d** [qbcore-framework/qb-ambulancejob#136]
**Describe the bug**
The bug was reported previously and it was dismissed and closed as "Cannot Reproduce" Here is a video of the bug and what is going on. Start to finish. I would recommend spamming the signin as well. 

**To Reproduce**
1. Get Shot
2. Spam Checkin
3. Get up
4. Never Die

**Expected behavior**
You will become perma God Mode unless an admin uses admin kill.

**Screenshots**
YouTube Video of This: So this Can Be Properly Reproduced - https://youtu.be/oERDfgaWOKA

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? NO

**Additional context**
None.

**Comment by MonkeyWhisper** [comment]
Thanks, do you have two triggers happening? 
![image](https://user-images.githubusercontent.com/82112471/155032830-1531ec8b-873c-4eef-bba5-90dcd5a40b6a.png)

**Comment by d-w00d** [comment]
This is just what appears after he has spammed the key so many times. If you just spam key it on the checkin it basically doubles it up I think.

**Comment by izMystic** [comment]
cant reproduce, i get 2 notifications for it, but no godmode

**Comment by d-w00d** [comment]
you're spamming the keyboard continually from checkin till you get to the bed?

**Comment by izMystic** [comment]
yep

**Comment by ALFAMAS** [comment]
> **Describe the bug** The bug was reported previously and it was dismissed and closed as "Cannot Reproduce" Here is a video of the bug and what is going on. Start to finish. I would recommend spamming the signin as well.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Get Shot
> 2. Spam Checkin
> 3. Get up
> 4. Never Die
> 
> **Expected behavior** You will become perma God Mode unless an admin uses admin kill.
> 
> **Screenshots** YouTube Video of This: So this Can Be Properly Reproduced - https://youtu.be/oERDfgaWOKA
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: Today
> * Are you using custom resource? which ones? No
> * Have you renamed `qb-` to something custom? NO
> 
> **Additional context** None.

Just stop the Progress bar and animation & Directly Send Ped to the Bed Works For me - No God Mode

**Comment by OwnerPlayz** [comment]
Steps to Reproduce the issue:
1. Go to Hospital
2. Press E to Lie on Bed.
3. Talk in Radio. 

After this you will have god mode.
