### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nelydde** [qbcore-framework/qb-ambulancejob#137]
Hello.

I don't do anything, i only use qb by qb-framework and I don't use other scipts.

I have : 
[script:qb-ambulancej] Error loading script server/main.lua in resource qb-ambulancejob: @qb-ambulancejob/server/main.lua:238: attempt to index a nil value (global 'Lang')
[script:qb-ambulancej] stack traceback:
[script:qb-ambulancej] @qb-ambulancejob/server/main.lua:238: in main chunk
[ c-scripting-core] Failed to load script server/main.lua.

I don't do anything

Anyone can help me please ?

Thank you !

**Comment by MonkeyWhisper** [comment]
Update your core to include the locale files.

**Comment by tgtgcuh** [comment]
> Update your core to include the locale files.

how
