### ISSUE TITLE
More than two teleporters?

### ISSUE THREAD

**Issue by W0lv3sxD** [qbcore-framework/qb-ambulancejob#157]
Hey, 

I changed from normal PillBox MLO to one with a Garage. Now I need more than the two current teleporters(Main -> Roof, Roof -> Main) but I dont know how to add them in this script. I need the following ones:

Roof -> Garage
Garage -> Roof
Main -> Garage
Garage -> Main

I hope I get help here

Thanks in advance

**Comment by Sinistermind81** [comment]
you'll need to add them yourself in  qb-smallresources

**Comment by parham-tehrani** [comment]
either just as said before, add them up yourself in smallresources, or just disable them under client/job, and just get the qb-lift script and set up restricted elevators according to each job

**Comment by uShifty** [comment]
Issue seems to be resolved, if you have any other questions or the issue is not resolved feel free to reopen the issue

**Comment by kokorog** [comment]
RegisterNetEvent('qb-ambulancejob:elevator_roof', function()
    local ped = PlayerPedId()
    local pos = GetEntityCoords(ped)
    for k, v in pairs(Config.Locations["roof"]) do
        local dist = #(pos - v)
                if dist < 1.5 then
        DoScreenFadeOut(500)
        while not IsScreenFadedOut() do
            Wait(10)
        end

        currentHospital = k

        local coords = Config.Locations["main"][currentHospital]
        SetEntityCoords(ped, coords.x, coords.y, coords.z, 0, 0, 0, false)
        SetEntityHeading(ped, coords.w)

        Wait(100)

        DoScreenFadeIn(1000)
    end
end
end)

RegisterNetEvent('qb-ambulancejob:elevator_main', function()
    local ped = PlayerPedId()
    local pos = GetEntityCoords(ped)
    for k, v in pairs(Config.Locations["main"]) do
        local dist = #(pos - v)
                if dist < 1.5 then
        DoScreenFadeOut(500)
        while not IsScreenFadedOut() do
            Wait(10)
        end

        currentHospital = k

        local coords = Config.Locations["roof"][currentHospital]
        SetEntityCoords(ped, coords.x, coords.y, coords.z, 0, 0, 0, false)
        SetEntityHeading(ped, coords.w)

        Wait(100)

        DoScreenFadeIn(1000)
    end
end
end)
