### ISSUE TITLE
When a person is injured on the ground

### ISSUE THREAD

**Issue by spartan111** [qbcore-framework/qb-ambulancejob#16]
When a person is injured on the ground, if you hit him, he can stand up and if he reacts quickly and clicks to hit, he can start fighting while being injured. more details https://streamable.com/u8yih7

**Comment by BerkieBb** [comment]
Can you test https://github.com/qbcore-framework/qb-ambulancejob/pull/17 @spartan111

**Comment by imbader** [comment]
also if a person passout while being escorted or seated in vehicle they will get ejected from vehicle
