### ISSUE TITLE
.

### ISSUE THREAD

**Issue by stewiehell** [qbcore-framework/qb-ambulancejob#165]
:)

**Comment by stewiehell** [comment]
[script:qb-ambulancej] Error loading script server/main.lua in resource qb-ambulancejob: citizen:/scripting/lua/scheduler.lua:867: No such export GetCoreObject in resource qb-core
[script:qb-ambulancej] stack traceback:
[script:qb-ambulancej] 	[C]: in function 'error'
[script:qb-ambulancej] 	citizen:/scripting/lua/scheduler.lua:867: in metamethod 'index'
[script:qb-ambulancej] 	@qb-ambulancejob/server/main.lua:3: in main chunk

**Comment by RilloX01** [comment]
tf is a 'wont work error'

**Comment by stewiehell** [comment]
vyhul čuráka

**Comment by stewiehell** [comment]
Prostě to nejde ty mrdko vyjebaná.

**Comment by stewiehell** [comment]
![image](https://user-images.githubusercontent.com/102426823/165039737-cf5f75b2-603f-4f63-a377-15828907db1b.png)

**Comment by uShifty** [comment]
Issue edited to be nothing? Reopen if this is an actual issue
