### ISSUE TITLE
[BUG] E prompt doesn't go away

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-ambulancejob#166]
The E prompt doesn't go away after you pull out the vehicle and if you hit E while flying, the vehicle despawns.

![20220421113425_1](https://user-images.githubusercontent.com/43043270/164497495-fedeea36-eeeb-4245-b4cf-ac70ddfab5d1.jpg)

**Comment by AaronWeber53** [comment]
I have the same thing, whenever I press E then it teleports me back to that helicopter pad

**Comment by OMikkel** [comment]
I am not able to replicate the bug, however, I found the above typo, maybe this has to do with the issue.

If more information is provided regarding how I would go about replicating the issue I am more than happy to test it.
![TbC3qJr](https://user-images.githubusercontent.com/57924435/165000087-4f1de84a-ae0b-4756-ad88-585461da774a.jpeg)

**Comment by erikmeyer08** [comment]
Tried the fix and still having the same issue.

**Comment by erikmeyer08** [comment]
OK so I'm and idiot and open and close brackets make a difference in your if statements.
Sorry to waste everyone's time!

What I had: `if isPointInside and PlayerJob.name =="ambulance" or PlayerJob.name =="fire" and onDuty then`
Changed to: `if isPointInside and (PlayerJob.name =="ambulance" or PlayerJob.name =="fire") and onDuty then`

**Comment by OMikkel** [comment]
In the future you have to make sure that you are running up to date code from main branch before marking it is a bug. 🙂
Would in fact be interesting to hear what changes @AaronWeber53 have made to produce this error.
