### ISSUE TITLE
get out of bed [BUG]

### ISSUE THREAD

**Issue by parham-tehrani** [qbcore-framework/qb-ambulancejob#169]
after setting up the bed locations in config.
when you check in . it puts you to the first bed. heals you up, charges you, after a while you get the "E get out of bed" after pressing E, it puts you to another bed, but your character is standing. you can't move, your only option is to press it (the option is not visible though) to get into that new bed and then get out of it...
when you go to bed, by standing beside it, it puts you to bed and charges you but does not heal you. and you can get out of it any time. (how do i stop it from charging me?)

**Comment by LateNightRP** [comment]
I am not having this issue as well. When you press "E" to get out of ped it spawns you out of ped and your ped becomes frozen in place.

**Comment by SarangGit** [comment]
-----before -----
bedCombo:onPlayerInOut(function(isPointInside)
            if isPointInside then
                inBed = true
                exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
                CheckInControls("beds")
            else
                inBed = false
                listen = false
                exports['qb-core']:HideText()
            end
        end)

-----after -------
bedCombo:onPlayerInOut(function(isPointInside)
            if isPointInside _**and not isInHospitalBed**_ then
                inBed = true
                exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
                CheckInControls("beds")
            else
                inBed = false
                listen = false
                exports['qb-core']:HideText()
            end
        end)

It worked for me

**Comment by SarangGit** [comment]
> I am not having this issue as well. When you press "E" to get out of ped it spawns you out of ped and your ped becomes frozen in place.

-----before -----
bedCombo:onPlayerInOut(function(isPointInside)
if isPointInside then
inBed = true
exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
CheckInControls("beds")
else
inBed = false
listen = false
exports['qb-core']:HideText()
end
end)

-----after -------
bedCombo:onPlayerInOut(function(isPointInside)
if isPointInside and not isInHospitalBed then
inBed = true
exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
CheckInControls("beds")
else
inBed = false
listen = false
exports['qb-core']:HideText()
end
end)

It worked for me

**Comment by SarangGit** [comment]
> after setting up the bed locations in config. when you check in . it puts you to the first bed. heals you up, charges you, after a while you get the "E get out of bed" after pressing E, it puts you to another bed, but your character is standing. you can't move, your only option is to press it (the option is not visible though) to get into that new bed and then get out of it... when you go to bed, by standing beside it, it puts you to bed and charges you but does not heal you. and you can get out of it any time. (how do i stop it from charging me?)

update the above code

**Comment by Fistsofury** [comment]
For those on the latest  this is Sarang latest fix including the code so you can search thats all
--Before--

            local bedCombo = ComboZone:Create(bedPoly, {name = "bedCombo", debugPoly = false})
            bedCombo:onPlayerInOut(function(isPointInside)
                if isPointInside then
                    exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
                    CheckInControls("beds")
                else
                    listen = false
                    exports['qb-core']:HideText()
                end
    --AFTER--
            bedCombo:onPlayerInOut(function(isPointInside)
                if isPointInside and not isInHospitalBed then
                    exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
                    CheckInControls("beds")
                else
                    inBed = false
                    listen = false
                    exports['qb-core']:HideText()
                end

**Comment by i-kulgu** [comment]
This is fixed within the latest version.
