### ISSUE TITLE
[BUG] EMS Checkin

### ISSUE THREAD

**Issue by NoobySloth** [qbcore-framework/qb-ambulancejob#170]
So, when 0 EMS are online you can check in but as soon as +1 EMS logs in and then logs out again it no longer lets you check in, the button says "Check In" but doesn't run anything.

Reproduce;

Try with 0 ems online
Get 1 ems in then they log out
then test check in

**Comment by erikmeyer08** [comment]
#175 This should fix it.

or just change your config to -1

**Comment by NoobySloth** [comment]
> #175 This should fix it.
> 
> or just change your config to -1

I have my config required for 2 doctors. 
So when more than 2 doctors log in it then calls the doctor at check-in instead of putting you on the bed.

Once those 2 doctors then leave, the trigger just doesn't work. It doesn't call any doctors and it doesn't put you in any beds.

**Comment by erikmeyer08** [comment]
Are you using the latest version? I think the updated pushed out the other day fixed that issue.

**Comment by NoobySloth** [comment]
> Are you using the latest version? I think the updated pushed out the other day fixed that issue.

Yes, recent, presuming you're on about #153 if so it's still doing what I stated above.. :( 
It's almost like the Check-In trigger is just useless, once the ems leave you try to click the check-in and it just does nothing.

**Comment by NoobySloth** [comment]
> Do you have your config set to 0?

Why would I have it set at 0 if I want it at 2 though?

**Comment by Zael98** [comment]
think the problem is when the script try to remove the doctor when he go off duty or change the job cause if u try to do a print (doctorCount) still with 1 doctor allways and never change to 0 for example, so this is the problem i think

**Comment by nzkfc** [comment]
> think the problem is when the script try to remove the doctor when he go off duty or change the job cause if u try to do a print (doctorCount) still with 1 doctor allways and never change to 0 for example, so this is the problem i think

lol this is still an issue ><
