### ISSUE TITLE
[BUG] Dies in prison and respawns at the hospital

### ISSUE THREAD

**Issue by Gambrino** [qbcore-framework/qb-ambulancejob#172]
Title is self explanatory, can someone provide me a snippet or at least put it on default if a person is in jail, they will spawn in jail instead of pillbox hospital.

**Comment by i-kulgu** [comment]
> Title is self explanatory, can someone provide me a snippet or at least put it on default if a person is in jail, they will spawn in jail instead of pillbox hospital.

You can add a check inside the LeaveBed() function.
So When you die, you go to hospital bed, you get your treatment and after getting out of bed you need to check if he was in jail and send him back.
What you can do is to edit the LeaveBed() function like this: 

`local function LeaveBed()
    local player = PlayerPedId()

    RequestAnimDict(getOutDict)
    while not HasAnimDictLoaded(getOutDict) do
        Wait(0)
    end

    FreezeEntityPosition(player, false)
    SetEntityInvincible(player, false)
    SetEntityHeading(player, bedOccupyingData.coords.w + 90)
    TaskPlayAnim(player, getOutDict , getOutAnim, 100.0, 1.0, -1, 8, -1, 0, 0, 0)
    Wait(4000)
    ClearPedTasks(player)
    TriggerServerEvent('hospital:server:LeaveBed', bedOccupying)
    FreezeEntityPosition(bedObject, true)
    RenderScriptCams(0, true, 200, true, true)
    DestroyCam(cam, false)

    bedOccupying = nil
    bedObject = nil
    bedOccupyingData = nil
    isInHospitalBed = false

       QBCore.Functions.GetPlayerData(function(PlayerData)
		if PlayerData.metadata["injail"] > 0 then
			TriggerEvent("prison:client:Enter", PlayerData.metadata["injail"])
		end
	end)
end`

**Comment by Gambrino** [comment]
> QBCore.Functions.GetPlayerData(function(PlayerData)
> 	if PlayerData.metadata["injail"] > 0 then
> 		TriggerEvent("prison:client:Enter", PlayerData.metadata["injail"])
> 	end
> end)

Thank you so much.

For those having problems like me, use this BUT make sure to remove the prisonbreak.lua file.
