### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ricok-dev** [qbcore-framework/qb-ambulancejob#179]
**Describe the bug**
There is a problem with the qb-targe interaction and the check-in option

**To Reproduce**
1. Go to 'the check-in location'
2. Interact with the third eye button
3. Nothing happens no options showing up

**Expected behavior**
See the check-in option and trigger the client event that heals the player

**Additional context**
I fix the problem by changing the name of the target (it would be silly to make a PR for this)

at line 894 change:

`name = "checkin"..k,` 
for
`name = "checking"..k,`

**Comment by uShifty** [comment]
I believe [#181](https://github.com/qbcore-framework/qb-ambulancejob/pull/181) is the change you requested which appeared to be the fix, Therefore this issue should be resolved if it is not resolved feel free to reopen the issue
