### ISSUE TITLE
Death timer

### ISSUE THREAD

**Issue by Hazzer278** [qbcore-framework/qb-ambulancejob#18]
When changing the Config.Deathtime no matter what value I put it stays at 400 seconds for me 

I feel like I'm not changing the right thing so if so please correct me aha

**Comment by ihyajb** [comment]
are you talking about last stand time?

**Comment by ihyajb** [comment]
if so last stand time is found at the top of laststand.lua
![image](https://user-images.githubusercontent.com/66404074/129427538-8db7f961-4038-4818-b4af-ddcfbc4181c4.png)

**Comment by Hazzer278** [comment]
Yes thats the one , Your a legend appreciate the help <3

**Comment by ihyajb** [comment]
anytime my man<3. If you dont need anymore help please close the issue.
