### ISSUE TITLE
[BUG] Check Status

### ISSUE THREAD

**Issue by TopperzDK** [qbcore-framework/qb-ambulancejob#180]
**Describe the bug**
Whenever at EMS tries to check status on a player, the menu comes up, but there is no status. i tried this when shooting, stabbing and hitting a player

**Expected behavior**
Would like to see player's status of wounds and such

**Screenshots**

![errorems](https://user-images.githubusercontent.com/22060074/168468003-05f19ddf-1b50-47c8-bbe6-08399dd21c01.png)

**Comment by dwiprizzy** [comment]
any update  for this bug

**Comment by DevKaedou** [comment]
This also happens to me, we can't identify the cause of death for EMS RP. Hope this could be resolved.

**Comment by elmschaym** [comment]
try to put this into your config.lua 

Config.MaxInjuryChanceMulti = 3

**Comment by wrathster2103** [comment]
Done the above, still not working for me

**Comment by GhostLegionRP** [comment]
still not working
