### ISSUE TITLE
bleeding out causes kicked out of car/un-carry [BUG]

### ISSUE THREAD

**Issue by Monkey1995** [qbcore-framework/qb-ambulancejob#187]
when the person bleeds out if they are in a car or being carried it will put them out the car or stop the player from carrying the person that has just bleed out

**To Reproduce**
1. kill yourself
2. get some one to carry you or put you in a car until the bleed out timer runs out
3. when the timer runs out it will stop the other person from carrying you or it will throw you from the car

**Expected behavior**
to carry on carrying the person/ they don't fall out of the car

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 
       last weekish
 - Are you using custom resource? 
        a lot of custom resources but it happens on a fresh install as well
 - Have you renamed `qb-` to something custom? 
        no

**Comment by Flying-Turtles2** [comment]
I wouldn't really call that a bug though if they bleed out because the timer ran out then that essentially means they died. If for you server you don't want players to bleed out then you should instead look for a way to either disable the timer or just set it to a much higher time

**Comment by dennrick** [comment]
> I wouldn't really call that a bug though if they bleed out because the timer ran out then that essentially means they died. If for you server you don't want players to bleed out then you should instead look for a way to either disable the timer or just set it to a much higher time 

I don't agree with this. If you are transporting someone who is downed to get treatment they shouldn't fall out of your arms because they "die". You'd still be holding them.

**Comment by Flying-Turtles2** [comment]
I understand your frustration with that and I'm telling you I'm order to fix it make your bleed out time longer because when the player bleeds out if I'm not mistaken that players screen blacksout for just a moment and for some GTA reason if the players screen blacksout it freezes them in place as it changes their state from downed to dead that's what causes you to drop the player even if you are carrying then in a car

**Comment by Monkey1995** [comment]
> I understand your frustration with that and I'm telling you I'm order to fix it make your bleed out time longer because when the player bleeds out if I'm not mistaken that players screen blacksout for just a moment and for some GTA reason if the players screen blacksout it freezes them in place as it changes their state from downed to dead that's what causes you to drop the player even if you are carrying then in a car

If i do this and there are no EMS in city people will be sitting there waiting for ages, i think its a bug in my opinion as @dennrick said if your carrying some one and they die you wouldn't just drop them or they wouldn't just fall out of the car

**Comment by FrequencyRoleplay** [comment]
its how the game operates .  its not a bug.

**Comment by daf4ever** [comment]
> its how the game operates . its not a bug.

And how do you turn it off? I just got into the city, drove 1min and suddenly I got kicked out of my car while I was driving on the highway and because of the kick out of the car I insta died.

**Comment by daf4ever** [comment]
and it just happend again. I am at full health and I get kicked out of the car because of bleeding that I don't know where I got because my health was full...
