### ISSUE TITLE
Optional distress signal

### ISSUE THREAD

**Issue by 12Echo** [qbcore-framework/qb-ambulancejob#189]
Instead of just immediately sending a distress signal to ems upon death, it'd be nice if the person can press a button to send it after dying.

**Comment by 12Echo** [comment]
> You can press G to send a distress signal after a certain period of time. If you want to remove the auto-alerts :
> 
> On client/dead.lua comment out line 54 : TriggerServerEvent('hospital:server:ambulanceAlert', Lang:t('info.civ_died'))
> 
> And on client.laststand.lua, comment out line 72 : TriggerServerEvent('hospital:server:ambulanceAlert', Lang:t('info.civ_down'))

Hey, thank you! That worked, but I was wondering if you know how I can make it so they get a distress signal option both when they first die & when they go into the final stand. (So they can send a total of 2 distress signals)

**Comment by nzkfc** [comment]
Might totally be the wrong way for sure, but off the top of my head without fully reemembering the configs, you could just make the last stand longer and the first stage much shorter, like 1 min, then that way they can press G for distress?
