### ISSUE TITLE
on off duty 

### ISSUE THREAD

**Issue by Undeaddragon32** [qbcore-framework/qb-ambulancejob#19]
hey i have the problem that the on and off duty is not displayed when im right on the spot where it is and i dont know what i did wrong 
![Screenshot_16](https://user-images.githubusercontent.com/88719513/128865844-af92dd82-2cd5-4b4b-88d7-b9c62a246dff.png)

**Comment by BerkieBb** [comment]
You have to be logged in for it to show, for that after restarting the resource you have to do /logout

**Comment by Undeaddragon32** [comment]
what i mean with it is this 
![68747470733a2f2f696d6775722e636f6d2f354654616763472e706e67](https://user-images.githubusercontent.com/88719513/128957024-4fe9a6cb-60ae-44c9-a00f-4d67e7089e28.png)
