### ISSUE TITLE
[BUG] after a player dies it takes a few seconds to register you dead

### ISSUE THREAD

**Issue by StopaEntertainment** [qbcore-framework/qb-ambulancejob#191]
for example, you don't immediately die when you get to 0 health, more like 5 seconds after.

if a player f8 quits during that 5 seconds and rejoins, they spawn with full health and alive.

also, if you for example go flying out the windshield of a car, it will teleport you to a random place inside that time before you landed on the ground and you will fully die from it spawning you midair and your body hitting the ground

VIDEO: https://medal.tv/games/gta-v/clips/nlC2lg-8sg1bL/d1337ZbHQudx?invite=cr-MSx4N3MsMjI4MjcyNTYs

**Comment by iDazza** [comment]
anyone fix this issue? im having this issue?

**Comment by amsali22** [comment]
they will never fix this just dont wait
