### ISSUE TITLE
[BUG] attempt to compare nil with number client/main.lua:87

### ISSUE THREAD

**Issue by K-19-2** [qbcore-framework/qb-ambulancejob#194]
**Describe the bug**
attempt to compare nil with number client/main.lua:87

**To Reproduce**
1. Trigger IsDamagingEvent function
2. Get attempt to compare nil with number @qb-ambulancejob/client/main.lua:87 error in F8

**Expected behavior**
make comparisons for the number

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: a few days ago
 - Are you using custom resource? which ones? default qb-ambulancejob
 - Have you renamed `qb-` to something custom? no

**Additional context**
missing Config.MaxInjuryChanceMulti value in the config, leading to a possible nil comparison

**Comment by singh-manavv** [comment]
Unable to reproduce this issue
