### ISSUE TITLE
[SUGGESTION] new dead state

### ISSUE THREAD

**Issue by TonybynMp4** [qbcore-framework/qb-ambulancejob#199]
A K.O state similar to the laststand but you could get up after 60 seconds for example, would be used on minor injuries (fist fights for example) while gun injuries etc would still make you go in laststand.

**Comment by LightUpFam** [comment]
yes pleaseeeeeeeee

**Comment by Odyssey808** [comment]
I have seen this on a server before, I don't know how they did it. Trying to figure it out now.
