### ISSUE TITLE
[BUG]Can NOT close map when character down

### ISSUE THREAD

**Issue by MaMaster** [qbcore-framework/qb-ambulancejob#202]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'state bleed out but not down'
2. Open map and zoom out 
3. Wait until character down
4. Can NOT close map

**Expected behavior**
Close map still works when player down

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated:  updated two days ago
 - Are you using custom resource? which ones? [NO]
 - Have you renamed `qb-` to something custom? [NO]

**Additional context**

**Comment by MaMaster** [comment]
Can NOT close map when character down

**Comment by MaMaster** [comment]
updated two days ago

**Comment by singh-manavv** [comment]
Couldn't reproduce this either , most of the controls are disbaled after you enter last stand so they shouldn't even be able to open the map
