### ISSUE TITLE
[SUGGESTION] New log for player causing last stand to trigger

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-ambulancejob#204]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
There is a death log, but it would be nice to have a last stand log, so for example if a player shoots someone and they go into last stand, then it logs it as ['laststand'] or similar. There may be need to configure it for example weapons only or similar.

**Describe alternatives you've considered**
Don't think there much else here, just adding a new log option.

**Comment by Galactuuus** [comment]
This log wouldn´t be the same ¿? i mean the death log is the same as your last stand. Maybe i get wrong your idea

**Comment by nzkfc** [comment]
One log for being down and one for dead. E.g a log if someone shot you and
results in going down, then another log if that shooter finishes you off
(double head tap or whatever)
