### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DudeBroMate** [qbcore-framework/qb-ambulancejob#210]
**Describe the bug**
When you change the Config.DeathTimer, it doesn't change it in game. E.g. If I made the timer 30 seconds, it will still make players wait 400 seconds.

**To Reproduce**
1. Go to qb-ambulancejob > config.lua > line 8 and change the time in seconds
2. Ensure the script/restart server
3. Go in game and do /kill
4. Wait 400 seconds rather than the configured time

**Expected behavior**
The time I input for Config.DeathTimer should be the same time I inputted

**Screenshots**
[![image](https://user-images.githubusercontent.com/42883891/180683187-7d8e58f3-125d-414a-aedc-d87586e68e80.png)](https://cdn.discordapp.com/attachments/1000690865360076870/1000957037833900132/Bug1.PNG)

[![Bug2](https://user-images.githubusercontent.com/42883891/180683970-3d006085-419f-4dc7-88dc-040d1dae8082.PNG)](https://cdn.discordapp.com/attachments/1000690865360076870/1000957627674677278/Bug2.PNG)

**Questions (please complete the following information):**
 - When you last updated: 15 minutes ago
 - Are you using custom resource? which ones?: Nothing that should alter
 - Have you renamed `qb-` to something custom?: No

**Additional context**
Just want to make it so that members can wait more/less than 5 minutes

**Comment by 0xSavageD** [comment]
I believe what you are looking for is located in the laststand.lua. 
The two values you would change are Laststand.ReviveInterval and
Laststand.MinimumRevive.
