### ISSUE TITLE
[BUG] Jail beds not working showing "Beds Occupied" 

### ISSUE THREAD

**Issue by SirOMGitsYOU** [qbcore-framework/qb-ambulancejob#212]
**Describe the bug**
Attempting to check in at the prison check-in desk and get assigned a jail bed fails and gives the error prompt "Beds Occupied" even though beds are entirely empty

**To Reproduce**
1. Go to prison (jailed or not jailed)
2. Try check-in at the front desk
3. Receive error message and be unable to be checked-in

**Expected behavior**
Check in and be placed on the bed

**Questions (please complete the following information):**
 - When you last updated: Yesterday
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? no

**Comment by i-kulgu** [comment]
Use fix #273
