### ISSUE TITLE
[BUG] Players Spawn Elsewhere From Initial Ejection From Vehicle/Death

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-ambulancejob#216]
**Describe the bug**
As soon as you drive over a certain speed or crash into an object or another vehicle causing you to get ejected, you are spawned elsewhere on the map down waiting for help but your character is changed into a default ped.

**To Reproduce**
1. Just get a car
2. Find a wall
3. Go Fast!
4. Once you are ejected, youll just spawn somewhere as a default ped

**Expected behavior**
Player is down but is spawned elsewhere on the map waiting for help, only way to revert your skin is to reload your character /reloadskin if using fivem appearance

**Screenshots**
No screenshot available

**Questions (please complete the following information):**
 - When you last updated: This week
 - Are you using custom resource? which ones? only default ambulancejob and a few others fivem appearance etc
 - Have you renamed `qb-` to something custom? no

**Additional context**
None at the moment.

**Comment by singh-manavv** [comment]
I'm unable to reproduce this issue , it may happen if you haven't setup your clothing properly . Please look into your clothing script
