### ISSUE TITLE
[BUG] Spawning with extras doesn't work

### ISSUE THREAD

**Issue by davoucci** [qbcore-framework/qb-ambulancejob#240]
**Describe the bug**
In the config we got an place for spawning vehicle with his extras, but it doesnt work.

**To Reproduce**
1. Go to garage
2. Click on the vehicle you configured with extras
3. Spawn the vehicle

**Expected behavior**
it should spawn with the correct extras

**Comment by jeann2013** [comment]
@davoucci Please show me a video or pictures show the error

**Comment by i-kulgu** [comment]
Have you setup the modelnames correct ?
Example:

["ambulance"] = { -- this is the model name for spawning
},
["ambumav"] = { -- this is another ambulance vehicle
}

**Comment by Sinistermind81** [comment]
im having the same issue, i have tried everything even took the working section from policejobs for take car and still wont load the extras via the function. but if i change code to this the extras work fine.

`function TakeOutVehicle(vehicleInfo)
    local coords = Config.Locations["vehicle"][currentGarage]
    QBCore.Functions.TriggerCallback('QBCore:Server:SpawnVehicle', function(netId)
        local veh = NetToVeh(netId)
        SetVehicleNumberPlateText(veh, Lang:t('info.amb_plate') .. tostring(math.random(1000, 9999)))
        SetEntityHeading(veh, coords.w)
        exports['LegacyFuel']:SetFuel(veh, 100.0)
        --[[if Config.VehicleSettings[vehicleInfo] ~= nil then
            print('has vehicleInfo')
            if Config.VehicleSettings[vehicleInfo].extras ~= nil then
                print('has vehicleInfo.extras')
                QBCore.Shared.SetDefaultVehicleExtras(veh, Config.VehicleSettings[vehicleInfo].extras)
            end
        end]]
        SetVehicleExtra(veh, 1, 0)
        SetVehicleExtra(veh, 2, 1)
        SetVehicleExtra(veh, 7, 1)
        SetVehicleExtra(veh, 3, 1)
        SetVehicleExtra(veh, 5, 1)
        SetVehicleDirtLevel(veh, 0.0)
        TaskWarpPedIntoVehicle(PlayerPedId(), veh, -1)
        TriggerEvent("vehiclekeys:client:SetOwner", QBCore.Functions.GetPlate(veh))
        SetVehicleEngineOn(veh, true, true)
    end, vehicleInfo, coords, true)
end`

**Comment by Jougito** [comment]
It really is a bug but it has a very easy solution without having to edit the script code.

You just have to put in the `VehicleSettings -> Extras` section the extras that you **DO** want it to have, do not put any extra with false because then they will come out random.

Example:

```
Config.VehicleSettings = {
    ["police"] = {
        ["extras"] = {
            ["1"] = true,
            ["4"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true
        },
        ["livery"] = 2
    }
}
```

Regards
