### ISSUE TITLE
Ambulance Job DrawText and Vehicle Spawn

### ISSUE THREAD

**Issue by ZayImperio** [qbcore-framework/qb-ambulancejob#241]
**Describe the bug**
Whenever we lay in a hospital bed wither it be by check in, last stand, or lay in bed. The Draw Text box on the left hand side does not populate correctly. It flickers on and off the screen at a very fast rate. Also, the vehicle markers do not populate on screen. We are able to TP to the cords and press e to open but it is a guess where it would be if we do not have the proper cords.

**Screenshots**
![bedbug](https://user-images.githubusercontent.com/113717940/190706910-90a3d6b8-f659-45e4-b942-a165c8dd69af.png)

**Questions (please complete the following information):**
 - When you last updated: Yesterday
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by ZayImperio** [comment]
https://user-images.githubusercontent.com/113717940/190707245-f0d186f2-fec7-436b-bb91-42e72156d980.mp4

**Comment by ZayImperio** [comment]
I have also grabbed a screenshot with polyzone debug enabled. I am unable to see the draw text to take out a vehicle. 
![Uploading 3567B413-DB78-49A8-928F-CE5507EA687E.png…]()

**Comment by ZayImperio** [comment]
![1AE20129-E18B-45DF-AB92-F4D4D0D35065](https://user-images.githubusercontent.com/113717940/191672092-0d6cd01f-58e6-4d8d-a3a1-b871feb3f4ae.png)

**Comment by HysteriaRP** [comment]
have you fixed this issue??? Im having the same problem, and others not even showing up :/

**Comment by i-kulgu** [comment]
This is not an issue anymore, it's fixed with the recent updates.
