### ISSUE TITLE
ReviveP

### ISSUE THREAD

**Issue by Timotines** [qbcore-framework/qb-ambulancejob#242]
The ambulancejob can't revive people, neither can you revive people with /revivep. I don't get any errors in the console nor in F8.

**Comment by Yisus73** [comment]
To revive you have to wait for the dead person to have 300s, if you want to change it this is the configuration to change:
in client/laststand.lua:
Laststand.MinimumRevive = 300

**Comment by i-kulgu** [comment]
> The ambulancejob can't revive people, neither can you revive people with /revivep. I don't get any errors in the console nor in F8.

Is this still an issue ? Can't reproduce it..
