### ISSUE TITLE
[BUG] Stuck in bed

### ISSUE THREAD

**Issue by FrequencyRoleplay** [qbcore-framework/qb-ambulancejob#244]
Ive tried a few different updates.  Ive experienced this a few times and have a good amount of reports.

when a player spawning in hospital bed, they hold E to get out of bed.  The player gets stuck in that location and cant run around except for a have small radius. sometimes you can get back into bed and revive again to fix.  Or head pop.

I hope im not the first to report this as ive been looking for a way to fix this.,

**Comment by LightUpFam** [comment]
i believe this has fixed the problem. 

```            bedCombo:onPlayerInOut(function(isPointInside)
                if isPointInside and not isInHospitalBed then
                inBed = true
                exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
                CheckInControls("beds")
                else
                inBed = false
                listen = false
                exports['qb-core']:HideText()
                end
            end)```

**Comment by Smitthyy** [comment]
Where did you put this snippet to fix it mate? I have the same issue at the moment

**Comment by FrequencyRoleplay** [comment]
ambulance job, i think client. just search for the bedcombo

**Comment by i-kulgu** [comment]
Tested with the latest version and it's not an issue anymore.
