### ISSUE TITLE
[BUG] Vehicle Spawning issue

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-ambulancejob#264]
**Describe the bug**
When grabbing a vehicle from the vehicle spawner, it's not giving you the keys. Works for the PD vehicle spawner, but not ambulance
**Expected behavior**
Spawn a vehicle, and get keys to it

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] few months ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Not applicable
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Comment by djraymond** [comment]
search for this in job.lua

vehiclekeys:client:SetOwner

if it isn't there add this to it job.lua  line 82 until 42

function TakeOutVehicle(vehicleInfo)
    local coords = Config.Locations["vehicle"][currentGarage]
    QBCore.Functions.TriggerCallback('QBCore:Server:SpawnVehicle', function(netId)
        local veh = NetToVeh(netId)
        SetVehicleNumberPlateText(veh, Lang:t('info.amb_plate') .. tostring(math.random(1000, 9999)))
        SetEntityHeading(veh, coords.w)
        exports['LegacyFuel']:SetFuel(veh, 100.0)
        TaskWarpPedIntoVehicle(PlayerPedId(), veh, -1)
        if Config.VehicleSettings[vehicleInfo] ~= nil then
            QBCore.Shared.SetDefaultVehicleExtras(veh, Config.VehicleSettings[vehicleInfo].extras)
        end
        TriggerEvent("vehiclekeys:client:SetOwner", QBCore.Functions.GetPlate(veh))
        SetVehicleEngineOn(veh, true, true)
    end, vehicleInfo, coords, true)
end

**Comment by TankinTom** [comment]
Totally forgot I had this open, it was the fuel export I didn't change, I was the stupid one.
