### ISSUE TITLE
[BUG] anyone know why this error happens?

### ISSUE THREAD

**Issue by owlel** [qbcore-framework/qb-ambulancejob#267]
![image](https://user-images.githubusercontent.com/122576774/212340915-cae56f03-053d-4aa2-b2da-0a9dbc407ffb.png)
![we](https://user-images.githubusercontent.com/122576774/212350915-86cb1b06-bc71-4265-95c5-e3a67c839760.PNG)
![ds](https://user-images.githubusercontent.com/122576774/212348842-829418e9-5646-45ad-999c-b0d82bea6b30.PNG)

![Capture](https://user-images.githubusercontent.com/122576774/212348352-bbfb5e35-15ba-4cf1-9814-ca8e03ecac93.PNG)
![1](https://user-images.githubusercontent.com/122576774/212348366-807cf87b-c4ed-4703-942b-55e78374d49f.PNG)

the qbambulance error. it keeps happening very randomly and the whole EMS script wont be in my game, ill have to reset resources and my server to fix it.. i understand its telling me something is nil but i cant tell what.

**Comment by HawkEye172** [comment]
> ![image](https://user-images.githubusercontent.com/122576774/212340915-cae56f03-053d-4aa2-b2da-0a9dbc407ffb.png) ![we](https://user-images.githubusercontent.com/122576774/212350915-86cb1b06-bc71-4265-95c5-e3a67c839760.PNG) ![ds](https://user-images.githubusercontent.com/122576774/212348842-829418e9-5646-45ad-999c-b0d82bea6b30.PNG)
> 
> ![Capture](https://user-images.githubusercontent.com/122576774/212348352-bbfb5e35-15ba-4cf1-9814-ca8e03ecac93.PNG) ![1](https://user-images.githubusercontent.com/122576774/212348366-807cf87b-c4ed-4703-942b-55e78374d49f.PNG)
> 
> the qbambulance error. it keeps happening very randomly and the whole EMS script wont be in my game, ill have to reset resources and my server to fix it.. i understand its telling me something is nil but i cant tell what.

hey do u still need help with this issue?

**Comment by Hotdog21x** [comment]
we are having the same issue is there a known fix?

**Comment by Hotdog21x** [comment]
We are having this same issue is there a fix?

**Comment by owlel** [comment]
> We are having this same issue is there a fix?

hey! yes there is, so if i can remember, it was an issue with the type of fuel i was using in my city. the fuel has to match the ambulance script- ambulance script has to match the fuel :) so say you're using ps-fuel, search for legacyfuel in the ambulance script because thats the fuel its using and just change it to whatever fuel you're using.
