### ISSUE TITLE
[SUGGESTION] Death ragdoll animation

### ISSUE THREAD

**Issue by unknownentity1337** [qbcore-framework/qb-ambulancejob#269]
please add a ragdoll animation after death, or put it in the configuration options, I don't want to start the animation after death, but following the last condition the player dies, I've tried it but it doesn't work

**Comment by MriKNG** [comment]
Just replace the animation with this:

SetPedToRagdoll(GetPlayerPed(-1), 1000, 1000, 0, 0, 0, 0)

**Comment by lMikki** [comment]
> Just replace the animation with this:
> 
> SetPedToRagdoll(GetPlayerPed(-1), 1000, 1000, 0, 0, 0, 0)

What should be changed in the code so that the player is sent to the ragdoll?

**Comment by ihaatesounds** [comment]
> Just replace the animation with this:
> 
> SetPedToRagdoll(GetPlayerPed(-1), 1000, 1000, 0, 0, 0, 0)

Where should I add this line?

**Comment by Hexney272** [comment]
Where need to add this line?

**Comment by ryan11444** [comment]
> Just replace the animation with this:
> 
> SetPedToRagdoll(GetPlayerPed(-1), 1000, 1000, 0, 0, 0, 0)

Where does this line go???

**Comment by SlapZaR** [comment]
yea where do we add this line ?

**Comment by AlfonzDivoch** [comment]
> Just replace the animation with this:
> 
> SetPedToRagdoll(GetPlayerPed(-1), 1000, 1000, 0, 0, 0, 0)

When i did it ragdolls but the character gets up and is put in the animationa gain even when there is no LoadAnim or something like that what should i do?
