### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by CottonMouthMax** [qbcore-framework/qb-ambulancejob#276]
Is there a way to allow players to carry friends into the hospital and check them in? So far, if you carry them and try to check them in, it checks you in while holding them.

**Comment by i-kulgu** [comment]
> Is there a way to allow players to carry friends into the hospital and check them in? So far, if you carry them and try to check them in, it checks you in while holding them.

Look at my PR : #275 
Test it out and approve if it works for you.

**Comment by CottonMouthMax** [comment]
im still super confused when it comes to were to put this. do i put it in the bottom of my qb-ambulance  server main or client main?

**Comment by i-kulgu** [comment]
> im still super confused when it comes to were to put this. do i put it in the bottom of my qb-ambulance server main or client main?

This is the repository thats holding the carry function: 

https://github.com/i-kulgu/qb-ambulancejob/tree/carry

You can download the folder, backup your ambulancejob and put the new one in.
Don't forget to add the triggers for radialmenu so it works.

**Comment by CottonMouthMax** [comment]
much appreciated!
