### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Uniixx** [qbcore-framework/qb-ambulancejob#282]
**Describe the bug**
When people dies they get charged twice. Basically, when they die and get sent to the hospital in a bed they are getting the prompt to "Lean on the bed" which charges them 2,000$ and after a few seconds they get prompt to get out of the bed. 
Also sometimes it says all beds are taken I have around 9 beds set.

**To Reproduce**
1. Die in any ways then wait for the timer and respawn at the hospital.

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? 
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 No

**Additional context**

**Comment by Uniixx** [comment]
It is due to line 952 to 971 in client/main.lua
```
        local bedPoly = {}
        for k, v in pairs(Config.Locations["beds"]) do
            bedPoly[#bedPoly+1] = BoxZone:Create(v.coords, 2.5, 2.3, {
                name="beds"..k,
                heading = -20,
                debugPoly = false,
                minZ = v.coords.z - 1,
                maxZ = v.coords.z + 1,
            })
            local bedCombo = ComboZone:Create(bedPoly, {name = "bedCombo", debugPoly = false})
            bedCombo:onPlayerInOut(function(isPointInside)
                if isPointInside then
                    exports['qb-core']:DrawText(Lang:t('text.lie_bed'), 'left')
                    CheckInControls("beds")
                else
                    listen = false
                    exports['qb-core']:HideText()
                end
            end)
        end
```

**Comment by CoZmoTheGod** [comment]
Ended up just removing this section of code. Disables checking in at beds so no double charge.
