### ISSUE TITLE
Client side death status causes unexpected death behaviour on reconnection

### ISSUE THREAD

**Issue by Scott1sh** [qbcore-framework/qb-ambulancejob#283]
**Describe the bug**
If you die and relog/disconnect/or server restart when you log back in you are semi-dead, you can walk about, but cannot access inventory nor can you be killed or handcuffed

I have reinstalled the script and the error still remains

**To Reproduce**
1. Die fully
2. Relog/F8 Quit
3. Log back in to server on same character

**Expected behavior**
When loading back into the server you should be back in a dead state

**Additional context**
```lua
SCRIPT ERROR: @qb-ambulancejob/client/dead.lua:148: attempt to compare number with nil
MainThrd fn (@qb-ambulancejob/client/dead.lua:148)
MainThrd/ SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @qb-ambulancejob/client/dead.lua:63: attempt to perform arithmetic on a nil value (global 'deathTime')
MainThrd/ DeathTimer (@qb-ambulancejob/client/dead.lua:63)
MainThrd/ ref (@qb-ambulancejob/client/job.lua:117)
MainThrd/ ref (@qb-core/client/functions.lua:7)
MainThrd/ fn (@qb-ambulancejob/client/job.lua:108)
```

See Coffee's investigation: 
https://github.com/qbcore-framework/qb-ambulancejob/issues/283#issuecomment-1484376941

**Comment by TomTheDark** [comment]
some of player have the same

**Comment by nicodu34** [comment]
Hello I have the same thing and the same error

**Comment by zwkf** [comment]
> some of player have the same

As far as I can see, this will be repeatable by all players.

**Comment by amantu-qbit** [comment]
@Scott1sh This issue is fixed on PR #285 You Can check and comment their your result

**Comment by LionGangRP** [comment]
To fix the issue In dead.lua change "deathTime = 0" to "local deathTime = 0" Thank 
WolfOfDiscørd#2168

**Comment by amantu-qbit** [comment]
No! What are You Saying @LionGangRP !
It's a Global Variable and it's necessary for other parts of codes to use it. See PR #285 It's the actual fix.
