### ISSUE TITLE
[BUG/QBCore] 0 HP but not really dead --> after revive not moveable

### ISSUE THREAD

**Issue by LsPlayer** [qbcore-framework/qb-ambulancejob#288]
When I get to 0 hp in my QBCore Server I fall to ground but I am not really dead. Then when I get revived I am still not moveable. When I started my server and I died I had a counter at the bottom which showed me a time until I am respawning but this is away now and I am not able to die correctly. Maybe you can help me...

**Comment by QBLes** [comment]
I have this same bug, somehow the person is broken and does not have a death timer, when this happens they hit "X" a few times puts them back on there feet and they can run around..

**Comment by QueenAFK** [comment]
Has anyone fixed this, currently have this issue

**Comment by MatthewBARP** [comment]
I'm also having the problem, might just download all my mods into one file, extract them and then completely restart the system and re-upload them all.
