### ISSUE TITLE
[SUGGESTION] QOL Features - Can we beef up content for EMS?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-ambulancejob#293]
**Is your feature request related to a problem? Please describe.**
A common feedback from EMS roleplay players is that it's incredibly boring, only function is to revive players, otherwise they drive around aimlessly and/or sit at hospital. The only time I have seen content made is by the players themselves either through deep medical RP or just rushing job to job on a busy server healing and going and the entire roleplay scene is fairly comical.

Police seem to have a bunch of functions; prop spawnings (cones etc), evidence, bullet casing, blood, trash, multiple avenues of RP. I see a few devs on CFX etc trying to enhance their role but it's not quite on par with Police currently. Would be nice if we can get a buff on features.

**Describe the feature you'd like**
Ideas:
- EMS bag option so server owners can choose if they get a EMS bag with stock out of armory or just use armory....... or both?
- EMS bag they carry and can put on ground then target it to get out items, maybe a small personal 6-slot stash in there for food/drink/phones etc
- EMS able to target players and take blood, then they get a blood pack. (blood packs can be used to craft some sort of item that relates to another idea further blow or similar???
- Diseases/STDs? - players have chance to get sick, that can spread, players go to EMS to get pills to cure it, would be cool if it went deeper in that they had to take a pill every hour they play otherwise they get sick up too X hours or X pills prescribed or something.
- Ability to put stretcher into the ambulance and attach the entity with the player on it, so they can finally pull it out and into hospital etc, at the moment it's not used at all i'm pretty sure.
- Make it so if you die and respawn at hospital bed, it will pick the closest hospital to the player and then onto those beds, e.g. if you die in grapeseed and have sandy MLO/hospital configured, you go to those beds (just like how Mythic hospital on ESX used to do it years ago)
- More options to add MRI/Surgery tables into the config so anyone using an MLO with one can easily set the table coords that players can push E on to lay down etc.

**Describe alternatives you've considered**
Tried asking 4 popular devs if they were keen for me to pay them to make this and then release it for free, as a PR or even to sell and all pretty much said no.

**Additional context**
I dunno, I just feel this part needs some love.

**Comment by MariusZmr** [comment]
I would love to implement these features.
I'll keep u updated.

**Comment by nzkfc** [comment]
Thanks, If you could also incorporate #299 into it once back shooter adds
logic to going to nearest hospital on death, this would give ambulance job
a huuuuge boost.
