### ISSUE TITLE
Paramedics can't heal any of their own injuries

### ISSUE THREAD

**Issue by JackBro2022** [qbcore-framework/qb-ambulancejob#298]
Paramedics can't heal any of their own injuries and I can't find a way to use the beds either if I click to check in, it just calls a doctor.

Note: testing this in a server with 0 other players just myself and I can't heal any of my own Wounds/Injurys without using an admin chat command eg: "/Revive" "/aheal" if I don't use either of them then I am just stuck permanently with injuries and continue to trip over without even moving.

Edit:
Also painkillers can't be used on my own person either, I take one it does the animation but I'm still in pain and receive 0 health benifits, same goes for banages I can use and it does the Animation but provides 0 improvement. And Medkits can't be self used period, it says it has to be used on someone else.

Edit 2: 
I have the latest version of the addon straight from here, there are not any other coflicting script/addons/etc.

**Comment by MariusZmr** [comment]
I've just checked that on my QBCore, and it seems to work perfectly, you cannot check in, but it doesn't mean that u cannot just go to the beds and heal urself there.
