### ISSUE TITLE
[SUGGESTION] - Emergency Services separate respawn time and fee

### ISSUE THREAD

**Issue by PavilonGaming** [qbcore-framework/qb-ambulancejob#307]
**Is your feature request related to a problem? Please describe.**
Currently Emergency Services has the same respawn/last stand timers as everyone else. 

**Describe the feature you'd like**
I would like to add a check for if the player is one of a configurable job table Config.EmergencyJobs = { "ambulance", "police", "mechanics"} and onDuty. If they are one of those jobs and onDuty then use a different set of timers so that these personnel can get back to work quicker to help other citizens. Also set a custom revive fee for those jobs that can be set separate from everyone else. 

**Describe alternatives you've considered**
have thought about reducing times for everyone but i also do not want to restrict roleplay for EMS personnel. and reducing times for everyone would mean less of a chance EMS would get to them in time

**Comment by Sharkiiie** [comment]
Just set the config variables for death time, etc. per job on the client.
if job = police then
deathtime = 150, etc.

**Comment by PavilonGaming** [comment]
> Just set the config variables for death time, etc. per job on the client. if job = police then deathtime = 150, etc.

i tried coding this out myself but never could get it to work right. being dead tired doesnt help, but i thought it would be a feature other servers may like as well
