### ISSUE TITLE
[BUG] Cant pull any vehicles out

### ISSUE THREAD

**Issue by TwoSmoove1** [qbcore-framework/qb-ambulancejob#309]
Everytime i try to pull out a ems vehicle i get this error
"SCRIPT ERROR: @qb-ambulancejob/client/job.lua:53: bad argument #1 to 'for iterator' (table expected, got nil)"
![error](https://github.com/qbcore-framework/qb-ambulancejob/assets/141871758/f72a8fee-fdc0-4a57-acc3-90d32535a5c0)

**Comment by Lana94681** [comment]
were you able to figure this out
