### ISSUE TITLE
SUGGESTION Move Blips to the config.lua

### ISSUE THREAD

**Issue by Mikkelmus** [qbcore-framework/qb-ambulancejob#31]
It could be really nice if you moved blips into the config file. so they are generated in the same way as in policejob it makes it easier if one like me has set up server to have 3-4 places people can get to the hospital.

it is a correction that I myself make every time an update comes to the job. but I have to enter client / main.lua myself. if it was in config it would just make the work of updating to new version much easier.

/mikkelmus

**Comment by GhzGarage** [comment]
Then why haven’t you made a pull request?

**Comment by Mikkelmus** [comment]
is brand new to Git....   and howto on git and funcktions i have not look after yet and i just edit the blips.. have not yet look in to do a recode så et works whit system like police job.

when i figure it ut i gladly pits in.

/Mikkelmus
