### ISSUE TITLE
[players are able to double checkin in hospital and unlimited infinity health getting activated]

### ISSUE THREAD

**Issue by AKGamingYT0988** [qbcore-framework/qb-ambulancejob#315]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'pillbox.'
2. Click on 'checkin 2 times instantly.'
3. Use this item 'infinite health activated' (item's name from shared.lua if applicable)

**Comment by AKGamingYT0** [comment]
till now no response . any one know their fix please share snippets
