### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nikolaaa24** [qbcore-framework/qb-ambulancejob#317]
**Describe the bug**
While signing in, if you click something you get a paper and pencil stuck in your hand forever until you leave the server.
**To Reproduce**
1. Go to pillbox hospital
2. Sign in
3. While signing in try clicking ESC or something

**Expected behavior**
Prop not stuck in my hand.

**Screenshots**
![1](https://github.com/qbcore-framework/qb-ambulancejob/assets/87242851/d7885496-4bac-44cc-93c8-ea33f5a04e43)

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? none
 - Have you renamed `qb-` to something custom? no

**Comment by brandon1808** [comment]
You can allways hit X on your keyboard and it should drop the paper and pencil  our of your hands
