### ISSUE TITLE
Need solution for this bug

### ISSUE THREAD

**Issue by WarLikePrince** [qbcore-framework/qb-ambulancejob#32]
found bug in check in not sure it is right to put this here

**Comment by GhzGarage** [comment]
I have no idea what you are talking about

**Comment by WarLikePrince** [comment]
sir actually someone shows me a bug which gives player advantage of godmode
with spamming of pillbox check in

**Comment by WarLikePrince** [comment]
i don't know someone found this but its working .  . spamming at pillbox
check in gives you an advantage of godmode. I think this bug has to be
fixed.
