### ISSUE TITLE
[BUG] Need to pay 2 times to respawn after a death

### ISSUE THREAD

**Issue by rapeurtueur** [qbcore-framework/qb-ambulancejob#321]
Hello , when we are dead and the cooldown is finish, we can press a button for respawn and pay...
When you press the button you are tp on the hospital
we need to pay 2 times to respawn after a death.

Go die
Wait the timer
Respawn 

Normaly we just need to pay one time alright ?

![image](https://github.com/qbcore-framework/qb-ambulancejob/assets/2059913/cc953102-3bfd-4477-b558-d1fe7c8933b1)
![image](https://github.com/qbcore-framework/qb-ambulancejob/assets/2059913/44e4226c-7790-4d76-a6f6-f4c9d5673fa1)
At this moment 2000€ are removed from the player

And after to quit the bed we pay again 2000€

**Comment by rapeurtueur** [comment]
First time:
![image](https://github.com/qbcore-framework/qb-ambulancejob/assets/2059913/b83b0ae6-3ac6-4c08-86e1-b807ca07ced2)
Seconds time when we quit the bed:
![image](https://github.com/qbcore-framework/qb-ambulancejob/assets/2059913/2adb50d5-8924-42bd-8074-b2e3fd8eba89)

**Comment by rapeurtueur** [comment]
And I forgot to say the script don't check if we have the money then we can do action without cash like I have -3875 €

**Comment by SinisterDevelopment** [comment]
have you tried to replace the script when a newer version?

are you using any 3rd party scripts that interact with this one?

**Comment by FortifiedGrizzly** [comment]
https://github.com/qbcore-framework/qb-ambulancejob/pull/326 < this fixes the double check in. and the cash going into minus, Is a qb-core setting. 

head over to qb-core // config.lua line 12 (on the latest version) QBConfig.Money.DontAllowMinus = { 'cash', 'crypto'}
