### ISSUE TITLE
[BUG] Laying bed not work with target.

### ISSUE THREAD

**Issue by HideMyFace** [qbcore-framework/qb-ambulancejob#334]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'hospital bed'
2. Click on ' the target on laying bed'
4. See the third eye not working and an error on console

**Expected behavior**
Go to bed and take $2000.

**Screenshots**
![image](https://github.com/qbcore-framework/qb-ambulancejob/assets/62813749/15d59a20-dd1b-48e6-90ed-aac1a2bc0d3b)

**Questions (please complete the following information):**
 - When you last updated: Today.
 - Are you using custom resource? which ones? No, I made some tests with the clean Qbcore.
 - Have you renamed `qb-` to something custom? No.

**Additional context**
With draw text it works fine.

**Comment by HideMyFace** [comment]
I didn't remember the "listsprite" function, I left it set to false and it worked

**Comment by DeKappaOfficial** [comment]
where or what did you change exactly? mine has the same issue and wont work...
