### ISSUE TITLE
[BUG] - Checking In Vector Doesn't Work When Changed/Moved To Elsewhere, Only Works At The Default Vector

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-ambulancejob#336]
Asd it says on the tin, in this case, this bugs title

I changed the vector from its default to a new location and boom, it doesn't work when someone tries to 'Check In'

**Comment by FoxeyBox** [comment]
I am also having this problem also there is no armoury in the Config for the ambulance anymore to put in bandages etc

**Comment by ChlxeThomson** [comment]
> I am also having this problem also there is no armoury in the Config for the ambulance anymore to put in bandages etc 


So make sure the checking in vector is the same as the Hospital vector & it will work
