### ISSUE TITLE
Problem with pillbox

### ISSUE THREAD

**Issue by Cervanga** [qbcore-framework/qb-ambulancejob#50]
i add a pilbox script to the framework and the default doors are still there and are preventing anyone for doing the job and healing players, how do i fix this?

**Comment by athena-git** [comment]
> 
> 
> i add a pilbox script to the framework and the default doors are still there and are preventing anyone for doing the job and healing players, how do i fix this?

Try disabling the PillboxHospital.Enable(false) in bob74_ipl (or whatever ipl loader you use)
