### ISSUE TITLE
[BUG] ambulancejob

### ISSUE THREAD

**Issue by sp19851** [qbcore-framework/qb-ambulancejob#56]
Markers do not appear after the device by the doctor

Reproduce

Set myself up a doctor job (/setjob [id] ambulance 2)
Installed hospital interior
I went to the places where the markers should be
Examined the code and suggested that the problem is in the new method isLoggedIn = LocalPlayer.state['isLoggedIn']

Questions (please fill in the following information):

When was the last time you updated: just before you tried
Are you using a custom resource? what?: no, fresh install
Have you renamed qb- to something custom?: No

**Comment by Skillgjii** [comment]
i have the same issue with a freash github install

**Comment by GhzGarage** [comment]
Should be fixed now https://github.com/qbcore-framework/qb-ambulancejob/commit/3a252fc486fea5529383755ead98283d33d3b0fc

**Comment by Skillgjii** [comment]
its fixed for check inn, but checkinn, arory and wehicle is gone.(prob elevators and heli gone to)
 is this the same problem ?

**Comment by GhzGarage** [comment]
Fix your config

**Comment by TaKtic1aN** [comment]
line 361 is still if isLoggedIn

**Comment by GhzGarage** [comment]
> line 361 is still if isLoggedIn client>job.lua needs changed to if LocalPlayer.state['isLoggedIn'] then

Still no PR 🤦🏻‍♂️
