### ISSUE TITLE
[ERROR] PROBLEMS

### ISSUE THREAD

**Issue by BennUzi** [qbcore-framework/qb-ambulancejob#59]
F8 Error

**Comment by BennUzi** [comment]
![image](https://user-images.githubusercontent.com/72662202/134819872-7e2a336e-4fdd-4bf8-9913-ce49a5f82e99.png)

**Comment by tomasalves8** [comment]
Have you made any changes to the resource? @BennUzi

**Comment by HATE-dev** [comment]
Apperantly you'r not using latest version of ambulancejob.

**Comment by ihyajb** [comment]
Could not reproduce, Using more recent QBCore resources. I suggest updating all your resources

**Comment by GhzGarage** [comment]
discord.gg/qbcore for support on this
