### ISSUE TITLE
Hospital check-in [BUG]

### ISSUE THREAD

**Issue by Slay3rIQ** [qbcore-framework/qb-ambulancejob#61]
After checking in in the hospital you are laying down on the ground instead of a bed.

![image](https://user-images.githubusercontent.com/90642225/135076394-78f6c4c0-2061-4b04-9d5a-68a26b4bd623.png)

**Comment by Rhydium** [comment]
This is because you are using a custom interior. Just change the coords for beds in the config and it'll work as intended.
