### ISSUE TITLE
[BUG] Log Problems

### ISSUE THREAD

**Issue by BennUzi** [qbcore-framework/qb-ambulancejob#68]
1 - Car Log Bug

System not sending notifications when crushing another player

2 - Death Log

It sends the system message to be sent from the 1st animation only after the player enters the 2nd animation, it must be sent in the first animation.

3 - Fall Log 

When a player falls from a height, it throws a vague system message or does not throw at all.

**Comment by zfbx** [comment]
This *might* be fixed with https://github.com/qbcore-framework/qb-ambulancejob/pull/80 but needed testing
