### ISSUE TITLE
[SUGGESTION] Stretcher

### ISSUE THREAD

**Issue by adweex** [qbcore-framework/qb-ambulancejob#75]
**Is your feature request related to a problem? Please describe.**
Unable to attach Stretcher to the Ambulance vehicle.

**Describe the feature you'd like**
Would be great if you could write a script that allows the stretcher to put into the vehicle. Or if it is already implemented, currently it doesen't work!

Thank you for your hard work!

**Comment by zfbx** [comment]
I believe a feature like that would require a vehicle that supports it to really be worth it. I'm curious how many people actually use the stretcher at all, most server's i've seen people just grab the person and put them in the vehicle

**Comment by xchopin** [comment]
Is this feature done?

**Comment by adweex** [comment]
> Is this feature done?

No. It is closed and scrapped.
