### ISSUE TITLE
[POTENTIAL BUG / FEATURE] Handcuffed upon respawning at hospital

### ISSUE THREAD

**Issue by GLaZeD-DoHNuTz** [qbcore-framework/qb-ambulancejob#81]
**Is your feature request related to a problem? Please describe.**

--> If someone is handcuffed, and they die, they would still have handcuffs on upon respawning at the hospital.

**Describe the feature you'd like**

--> I believe that if someone dies with handcuffs on, upon respawning at the hospital, the handcuffs should be automatically removed. I know EMS or police can uncuff, however, if there is no one on duty, then the player is running around with handcuffs on.

**Describe alternatives you've considered**

I also thought about a criminal getting away with handcuffs and dies. However, this would be a sticky discussion

**Additional context**

--> None, but I can take a clip if neccessary!

**Comment by zfbx** [comment]
if you wanna give that a test and see if it fixes the problem ^

**Comment by GLaZeD-DoHNuTz** [comment]
Ok I will check it out and let you all you! Thank You

**Comment by zfbx** [comment]
good to close?

**Comment by GLaZeD-DoHNuTz** [comment]
You can close this

**Comment by zfbx** [comment]
I can't lol you or GhzGarage would have to
