### ISSUE TITLE
[BUG] when i take the hele out i cant get in it and i can't go down in the élevator and this is the error i get

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-ambulancejob#84]
qb-ambulancejob/client/job => closeMenuFull() error 362

**Comment by MIguel-tech** [comment]
If you still have this problem try adding this at the bottom of qb-ambulancejob/client/job it worked for me
 function closeMenuFull()
    exports['qb-menu']:closeMenu()
end

> 
> 
> qb-ambulancejob/client/job => closeMenuFull() error 362

**Comment by OxGhali** [comment]
ok thnks i'll try it

**Comment by ansljeremy** [comment]
Should be good to close @OxGhali @GhzGarage
