### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Seraph1982** [qbcore-framework/qb-ambulancejob#88]
**Describe the bug**
I take an elevator to the roof , try to spawn a heli, it spawns but i´m not inside . and i have no key for it.
after /dv there is no elevator and no spawnpoint anymore 

**To Reproduce**
1. Go to 'roof'
2. use  'spawn helicopter'
3. use /dv and 
![consoleerror](https://user-images.githubusercontent.com/92158955/142030533-928cf7fb-7252-47da-b78d-39a1948b0815.png)

JOBGRADE 4

**Comment by zeemkarry** [comment]
same prob. ems cant use heli.

**Comment by ansljeremy** [comment]
Should be good to close @Seraph1982 @GhzGarage
