### ISSUE TITLE
[SUGGESTION] Changing Location of the Hospital

### ISSUE THREAD

**Issue by DonKDev** [qbcore-framework/qb-ambulancejob#98]
**Is your feature request related to a problem? Please describe.**
Hi I want to change the Hosptial Locations to another MLO but when i change the coordinates nothing is happening and the script is broke

**Describe the feature you'd like**
I would like to have a clear Documentation about how to change Locations, Menu Locations Spawns etc.

**Describe alternatives you've considered**
A good method should be an commented Config File that we can change completly and doesnt break up the script

**Comment by SkylarPlayz348** [comment]
this seems more like you need help because the config is editable and everything works for me ive even added a personal stash and it works so if you need help just go to the qb discord and ask for help there
